-- Migration: Add Assignment Schema
-- Date: 2026-02-24
-- Description: Create assignment_history table and vendedor_id column for lead assignment

-- ============================================================================
-- SECTION: Vendedor ID Column on Leads
-- ============================================================================

ALTER TABLE leads
ADD COLUMN vendedor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
ADD COLUMN atribuido_em TIMESTAMP NULL DEFAULT NULL;

COMMENT ON COLUMN leads.vendedor_id IS 'UUID of the salesperson assigned to this lead';
COMMENT ON COLUMN leads.atribuido_em IS 'Timestamp when lead was assigned';

-- Indexes
CREATE INDEX idx_leads_vendedor ON leads(vendedor_id);
CREATE INDEX idx_leads_atribuido ON leads(atribuido_em DESC);
COMMENT ON INDEX idx_leads_vendedor IS 'For querying leads by assigned vendedor';

-- ============================================================================
-- SECTION: Assignment History Table
-- ============================================================================

CREATE TABLE assignment_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  vendedor_anterior_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  vendedor_novo_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  motivo TEXT,
  atribuido_por_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  criado_em TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE assignment_history IS 'Audit trail for lead assignments and reassignments';
COMMENT ON COLUMN assignment_history.lead_id IS 'Reference to the lead';
COMMENT ON COLUMN assignment_history.vendedor_anterior_id IS 'Previous assignee (null if first assignment)';
COMMENT ON COLUMN assignment_history.vendedor_novo_id IS 'New assignee';
COMMENT ON COLUMN assignment_history.motivo IS 'Reason for reassignment';
COMMENT ON COLUMN assignment_history.atribuido_por_id IS 'User who made the assignment';

-- Indexes
CREATE INDEX idx_assignment_lead ON assignment_history(lead_id);
CREATE INDEX idx_assignment_vendedor_novo ON assignment_history(vendedor_novo_id);
CREATE INDEX idx_assignment_criado ON assignment_history(criado_em DESC);
COMMENT ON INDEX idx_assignment_lead IS 'For querying assignment history by lead';

-- ============================================================================
-- SECTION: Trigger - Record Assignment Changes
-- ============================================================================

CREATE OR REPLACE FUNCTION on_lead_assignment_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_user_id UUID;
BEGIN
  -- Record assignment change in history if vendedor_id changed
  IF (NEW.vendedor_id IS DISTINCT FROM OLD.vendedor_id) THEN
    -- Get current user from auth context (defaults to NULL if not available)
    BEGIN
      SELECT auth.uid() INTO v_current_user_id;
    EXCEPTION WHEN OTHERS THEN
      v_current_user_id := NULL;
    END;

    INSERT INTO assignment_history (
      lead_id,
      vendedor_anterior_id,
      vendedor_novo_id,
      atribuido_por_id,
      criado_em
    ) VALUES (
      NEW.id,
      OLD.vendedor_id,
      NEW.vendedor_id,
      v_current_user_id,
      NOW()
    );

    -- Update atribuido_em timestamp
    NEW.atribuido_em := NOW();
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_lead_assignment_change ON leads;
CREATE TRIGGER trg_lead_assignment_change
BEFORE UPDATE ON leads
FOR EACH ROW
EXECUTE FUNCTION on_lead_assignment_change();

COMMENT ON TRIGGER trg_lead_assignment_change ON leads IS 'Record assignment changes in assignment_history table';

-- ============================================================================
-- SECTION: Stored Procedures - Distribution Logic
-- ============================================================================

-- Round-robin assignment: returns next vendedor in rotation
CREATE OR REPLACE FUNCTION next_in_rotation()
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_next_vendedor_id UUID;
  v_lead_count INT;
BEGIN
  -- Get active vendedores (role = 'vendedor') sorted by current lead count
  SELECT u.id INTO v_next_vendedor_id
  FROM auth.users u
  LEFT JOIN leads l ON u.id = l.vendedor_id AND l.deleted_at IS NULL
  WHERE u.role = 'vendedor' AND u.deleted_at IS NULL
  GROUP BY u.id
  ORDER BY COUNT(l.id) ASC, u.id  -- Ascending count (lowest first), then by ID for tie-breaking
  LIMIT 1;

  RETURN COALESCE(v_next_vendedor_id, NULL);
END;
$$;

COMMENT ON FUNCTION next_in_rotation() IS 'Return next vendedor for round-robin assignment (lowest load first)';

-- Smart assignment: assigns to best fit (round-robin for now)
CREATE OR REPLACE FUNCTION calc_best_vendor_for_assignment()
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- For MVP: use round-robin (same as next_in_rotation)
  -- Future: can add scoring based on performance, specialization, probability match, etc.
  RETURN next_in_rotation();
END;
$$;

COMMENT ON FUNCTION calc_best_vendor_for_assignment() IS 'Calculate best vendedor for smart assignment (MVP: round-robin)';

-- ============================================================================
-- SECTION: Validation Queries (PRE-FLIGHT)
-- ============================================================================

-- Verify columns added
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'leads' AND column_name IN ('vendedor_id', 'atribuido_em');

-- Verify table created
-- SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'assignment_history';  -- Should be 1

-- Verify functions created
-- SELECT COUNT(*) FROM pg_proc WHERE proname IN ('next_in_rotation', 'calc_best_vendor_for_assignment');

-- Test round-robin (should return a UUID or NULL if no vendedores)
-- SELECT next_in_rotation();

-- ============================================================================
-- SECTION: ROLLBACK PROCEDURE
-- ============================================================================

-- To rollback this migration, run:
-- DROP TRIGGER trg_lead_assignment_change ON leads;
-- DROP FUNCTION on_lead_assignment_change();
-- DROP FUNCTION calc_best_vendor_for_assignment();
-- DROP FUNCTION next_in_rotation();
-- DROP TABLE assignment_history;
-- DROP INDEX idx_assignment_lead;
-- DROP INDEX idx_assignment_vendedor_novo;
-- DROP INDEX idx_assignment_criado;
-- ALTER TABLE leads DROP COLUMN atribuido_em;
-- ALTER TABLE leads DROP COLUMN vendedor_id;
-- DROP INDEX idx_leads_vendedor;
-- DROP INDEX idx_leads_atribuido;
