-- Migration: Add Forecasting Schema
-- Date: 2026-02-24
-- Description: Create forecasting_history table and probabilidade column on cards

-- ============================================================================
-- SECTION: Forecasting History Table
-- ============================================================================

CREATE TABLE forecasting_history (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  card_id BIGINT NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  data_snapshot DATE NOT NULL,
  probabilidade INT NOT NULL CHECK (0 <= probabilidade AND probabilidade <= 100),
  valor_provavel DECIMAL(12, 2),
  receita_real DECIMAL(12, 2) NULL,
  criado_em TIMESTAMP DEFAULT NOW(),

  CONSTRAINT unique_forecasting_snapshot UNIQUE(card_id, data_snapshot)
);

COMMENT ON TABLE forecasting_history IS 'Historical snapshots of lead probability and forecasted revenue';
COMMENT ON COLUMN forecasting_history.card_id IS 'Reference to the lead card';
COMMENT ON COLUMN forecasting_history.data_snapshot IS 'Date of the probability snapshot';
COMMENT ON COLUMN forecasting_history.probabilidade IS 'Probability of closing (0-100)';
COMMENT ON COLUMN forecasting_history.valor_provavel IS 'Forecasted revenue value';
COMMENT ON COLUMN forecasting_history.receita_real IS 'Actual revenue if deal closed';

-- Indexes for performance
CREATE INDEX idx_forecasting_card_snapshot ON forecasting_history(card_id, data_snapshot DESC);
CREATE INDEX idx_forecasting_probability ON forecasting_history(probabilidade DESC);
COMMENT ON INDEX idx_forecasting_card_snapshot IS 'For querying forecast history by card';

-- ============================================================================
-- SECTION: Probabilidade Column on Cards
-- ============================================================================

ALTER TABLE cards
ADD COLUMN probabilidade INT DEFAULT 0 CHECK (0 <= probabilidade AND probabilidade <= 100);

COMMENT ON COLUMN cards.probabilidade IS 'Current probability of closing (0-100), calculated by stored procedure';

-- ============================================================================
-- SECTION: Stored Procedure - Calculate Probability
-- ============================================================================

CREATE OR REPLACE FUNCTION calculate_probability(p_card_id BIGINT)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_lead_id BIGINT;
  v_etapa VARCHAR;
  v_dias_na_etapa INT;
  v_prob_base INT;
  v_prob_ajuste INT;
  v_prob_final INT;
  v_origem VARCHAR;
  v_valor_contrato DECIMAL;
BEGIN
  -- Get lead info
  SELECT l.id, c.etapa, c.origem, l.contract_value,
         EXTRACT(DAY FROM (NOW() - c.data_entrada_etapa))::INT AS dias
  INTO v_lead_id, v_etapa, v_origem, v_valor_contrato, v_dias_na_etapa
  FROM cards c
  JOIN leads l ON c.lead_id = l.id
  WHERE c.id = p_card_id;

  -- Base probability by stage
  v_prob_base := CASE v_etapa
    WHEN 'qualifier' THEN 20
    WHEN 'demo' THEN 40
    WHEN 'proposal' THEN 65
    WHEN 'negotiation' THEN 75
    WHEN 'contract' THEN 85
    WHEN 'won' THEN 100
    ELSE 0
  END;

  -- Adjust for days in stage (-2% per 10 days, max -30%)
  v_prob_ajuste := GREATEST(-30, -2 * (v_dias_na_etapa / 10));

  -- Adjust for origin (+20% referral, -5% web)
  v_prob_ajuste := v_prob_ajuste + CASE v_origem
    WHEN 'referral' THEN 20
    WHEN 'web' THEN -5
    ELSE 0
  END;

  -- Adjust for deal size (>100k +5%, <20k -5%)
  v_prob_ajuste := v_prob_ajuste + CASE
    WHEN v_valor_contrato > 100000 THEN 5
    WHEN v_valor_contrato < 20000 THEN -5
    ELSE 0
  END;

  -- Final probability (clamped 0-100)
  v_prob_final := GREATEST(0, LEAST(100, v_prob_base + v_prob_ajuste));

  RETURN v_prob_final;
END;
$$;

COMMENT ON FUNCTION calculate_probability(BIGINT) IS 'Calculate probability of closing for a lead card based on stage, days in stage, origin, and deal size';

-- ============================================================================
-- SECTION: Trigger - Recalculate Probability on Stage Change
-- ============================================================================

CREATE OR REPLACE FUNCTION on_card_stage_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Update probabilidade on stage change
  IF NEW.etapa != OLD.etapa THEN
    NEW.probabilidade := calculate_probability(NEW.id);

    -- Record snapshot in forecasting_history
    INSERT INTO forecasting_history (card_id, data_snapshot, probabilidade, valor_provavel, criado_em)
    VALUES (NEW.id, CURRENT_DATE, NEW.probabilidade, COALESCE(NEW.contract_value * NEW.probabilidade / 100, 0), NOW())
    ON CONFLICT (card_id, data_snapshot) DO UPDATE
    SET probabilidade = NEW.probabilidade,
        valor_provavel = COALESCE(NEW.contract_value * NEW.probabilidade / 100, 0);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_card_stage_change ON cards;
CREATE TRIGGER trg_card_stage_change
BEFORE UPDATE ON cards
FOR EACH ROW
EXECUTE FUNCTION on_card_stage_change();

COMMENT ON TRIGGER trg_card_stage_change ON cards IS 'Recalculate probability when stage changes and record in history';

-- ============================================================================
-- SECTION: Validation Queries (PRE-FLIGHT)
-- ============================================================================

-- Verify table created
-- SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'forecasting_history';  -- Should be 1

-- Verify trigger created
-- SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_name = 'trg_card_stage_change';  -- Should be 1

-- Test function
-- SELECT calculate_probability(1);  -- Should return 0-100

-- ============================================================================
-- SECTION: ROLLBACK PROCEDURE
-- ============================================================================

-- To rollback this migration, run:
-- DROP TRIGGER trg_card_stage_change ON cards;
-- DROP FUNCTION on_card_stage_change();
-- DROP FUNCTION calculate_probability(BIGINT);
-- DROP TABLE forecasting_history;
-- ALTER TABLE cards DROP COLUMN probabilidade;
